# Generated by Django 3.1.7 on 2021-12-24 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mahsool',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام محصول را وارد کنید')),
                ('info', models.TextField(max_length=2000, verbose_name='توضیحات محصول را اینجا بنویسید')),
                ('code', models.CharField(default=market.models.random_string, max_length=5, primary_key=True, serialize=False, verbose_name='کد محصول توسط سیستم تعیین می شود')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)], verbose_name='قیمت محصول را به تومان وارد کنید')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='تعداد محصول')),
                ('ofer', models.PositiveIntegerField(default='0', validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='درصد تخفیف')),
                ('img', models.ImageField(upload_to='home/', verbose_name='تصویر محصول را انتخاب کنید')),
                ('data', models.DateTimeField(verbose_name='تاریخ و ساعت زمان ثبت محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='چه کسی این کار را انجام می دهد')),
            ],
        ),
    ]
