# Generated by Django 3.1 on 2021-12-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='amount',
            field=models.BigIntegerField(verbose_name='قیمت محصول را به تومان وارد کنید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.BigIntegerField(default='47234', max_length=5, verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='data',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت زمان ثبت محصول'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='تصویر محصول را انتخاب کنید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='info',
            field=models.TextField(verbose_name='توضیحات محصول را اینجا بنویسید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محصول را وارد کنید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='چه کسی این کار را انجام می دهد'),
        ),
    ]
