# Generated by Django 3.1.7 on 2021-12-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ddk'),
        ),
    ]
