# Generated by Django 3.1.7 on 2021-12-24 12:35

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsool',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.CharField(default=market.models.random_string, max_length=5, primary_key=True, serialize=False, verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
    ]
