# Generated by Django 3.1 on 2021-12-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20211218_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.IntegerField(default='26544', max_length=5, verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
    ]
