# Generated by Django 3.1.7 on 2021-12-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_auto_20211224_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('userid', models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(editable=False, max_length=5, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('comment_text', models.TextField(max_length=2000, verbose_name='متن پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='چه کسی این کار را انجام می دهد')),
            ],
        ),
    ]
