# Generated by Django 3.1 on 2021-12-18 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20211218_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsool',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.IntegerField(default=27217, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
    ]
