# Generated by Django 3.1.7 on 2021-12-21 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20211221_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.PositiveIntegerField(default='79693', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='img',
            field=models.ImageField(upload_to='home/', verbose_name='تصویر محصول را انتخاب کنید'),
        ),
    ]
