# Generated by Django 3.1.7 on 2021-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.CharField(max_length=5, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(editable=False, max_length=50, verbose_name='کاربر'),
        ),
    ]
