# Generated by Django 3.1 on 2021-12-18 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20211218_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='قیمت محصول را به تومان وارد کنید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.PositiveIntegerField(default=69930, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='info',
            field=models.TextField(max_length=2000, verbose_name='توضیحات محصول را اینجا بنویسید'),
        ),
    ]
