# Generated by Django 3.1 on 2021-12-18 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20211219_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)], verbose_name='قیمت محصول را به تومان وارد کنید'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.PositiveIntegerField(default=21322, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
    ]
