# Generated by Django 3.1 on 2021-12-18 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20211219_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.PositiveIntegerField(default=58180, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='img',
            field=models.ImageField(upload_to='uploads/', verbose_name='تصویر محصول را انتخاب کنید'),
        ),
    ]
