# Generated by Django 3.1.7 on 2021-12-20 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20211220_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='code',
            field=models.PositiveIntegerField(default='85694', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='کد محصول توسط سیستم تعیین می شود'),
        ),
    ]
